# -*- coding: utf-8 -*-
"""aqf_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnSC3cZfeTLt02mRGF_qqcUSmg0HzlNO
"""

!pip install streamlit joblib tensorflow scikit-learn pandas numpy
!npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Conv1D, MaxPooling1D, Bidirectional, LSTM, Dense, Dropout
# 
# # Set page layout and title
# st.set_page_config(
#     page_title="Air Quality Forecasting & Audit System",
#     page_icon="🌬️",
#     layout="wide"
# )
# 
# st.title("🌬️ Air Quality Index (AQI) Forecasting App")
# st.write("This application uses **XGBoost Baseline Regression** and **CNN-BiLSTM Deep Learning** models to predict CO(GT) concentrations based on sensor metrics.")
# 
# # Define Feature Columns matching the notebook model
# FEATURE_COLS = ["PT08.S1(CO)", "PT08.S2(NMHC)", "PT08.S3(NOx)", "PT08.S5(O3)", "T", "RH", "AH"]
# TARGET_COL = "CO(GT)"
# LOOKBACK = 24  # 24-hour sequence length for CNN-BiLSTM model
# 
# # Load Pre-trained Models and Scalers
# @st.cache_resource
# def load_artifacts():
#     try:
#         xgb_model = joblib.load('xgboost_aqi_model.pkl')
#         scaler_X = joblib.load('scaler_X.pkl')
#     except Exception as e:
#         st.warning(f"Note on artifacts: Make sure 'xgboost_aqi_model.pkl' and 'scaler_X.pkl' exist in your directory. ({e})")
#         xgb_model = None
#         scaler_X = None
# 
#     return xgb_model, scaler_X
# 
# xgb_model, scaler_X = load_artifacts()
# 
# # Sidebar for Model Selection
# st.sidebar.header("Prediction Settings")
# model_option = st.sidebar.selectbox(
#     "Choose Prediction Model",
#     ["XGBoost Regressor (Baseline Table Input)", "CNN-BiLSTM (24-Hour Sequence Forecast)", "Batch CSV Upload & Evaluation"]
# )
# 
# # --- OPTION 1: Single Instance XGBoost Prediction ---
# if model_option == "XGBoost Regressor (Baseline Table Input)":
#     st.subheader("📊 Single-Timestamp Prediction (XGBoost)")
#     st.write("Enter the sensor values below to estimate current CO(GT) levels:")
# 
#     col1, col2, col3 = st.columns(3)
# 
#     with col1:
#         pt08_s1 = st.number_input("PT08.S1(CO) [Tin Oxide Sensor]", value=1360.0)
#         pt08_s2 = st.number_input("PT08.S2(NMHC) [Tungsten Oxide Sensor]", value=1046.0)
#         pt08_s3 = st.number_input("PT08.S3(NOx) [Tungsten Oxide Sensor]", value=1056.0)
# 
#     with col2:
#         pt08_s5 = st.number_input("PT08.S5(O3) [Indium Oxide Sensor]", value=1268.0)
#         temp = st.number_input("Temperature (°C)", value=13.6)
# 
#     with col3:
#         rh = st.number_input("Relative Humidity (%)", value=48.9)
#         ah = st.number_input("Absolute Humidity (AH)", value=0.7578)
# 
#     if st.button("Predict CO(GT)"):
#         input_data = pd.DataFrame([[pt08_s1, pt08_s2, pt08_s3, pt08_s5, temp, rh, ah]], columns=FEATURE_COLS)
# 
#         if xgb_model is not None:
#             prediction = xgb_model.predict(input_data)[0]
#             st.success(f"**Predicted CO(GT) Concentration:** {prediction:.2f} mg/m³")
#         else:
#             st.error("XGBoost model file 'xgboost_aqi_model.pkl' not found! Please train and save it first.")
# 
# # --- OPTION 2: CNN-BiLSTM 24-Hour Sequence Prediction ---
# elif model_option == "CNN-BiLSTM (24-Hour Sequence Forecast)":
#     st.subheader("🧠 CNN-BiLSTM Deep Learning Forecasting")
#     st.write("This model requires a **24-hour sequence** of past hourly sensor data to forecast CO(GT).")
# 
#     uploaded_file = st.file_uploader("Upload CSV containing at least 24 recent sensor readings:", type=["csv"])
# 
#     if uploaded_file is not None:
#         df = pd.read_csv(uploaded_file)
# 
#         # Preprocessing as per notebook: Replace -200 with NaN
#         df.replace(-200, np.nan, inplace=True)
# 
#         # Check feature presence
#         if all(col in df.columns for col in FEATURE_COLS):
#             # Impute missing values with column means
#             df_features = df[FEATURE_COLS].copy()
#             df_features.fillna(df_features.mean(), inplace=True)
# 
#             st.write("Uploaded Recent Data Preview:", df_features.tail(LOOKBACK))
# 
#             if len(df_features) >= LOOKBACK:
#                 if st.button("Run Deep Learning Prediction"):
#                     # Get last 24 records
#                     sequence_data = df_features.tail(LOOKBACK).values
# 
#                     if scaler_X is not None:
#                         # Scale input features
#                         scaled_seq = scaler_X.transform(sequence_data)
#                         scaled_seq = np.expand_dims(scaled_seq, axis=0) # Shape: (1, 24, 7)
# 
#                         # Reconstruct CNN-BiLSTM Model Architecture matching notebook
#                         dl_model = Sequential([
#                             Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(LOOKBACK, len(FEATURE_COLS))),
#                             MaxPooling1D(pool_size=2),
#                             Dropout(0.2),
#                             Bidirectional(LSTM(50, activation="tanh", return_sequences=False)),
#                             Dropout(0.2),
#                             Dense(32, activation='relu'),
#                             Dense(1)
#                         ])
# 
#                         # Note: In production, load trained weights: dl_model.load_weights('cnn_bilstm_model.h5')
#                         st.info("Generating sequence forecast with Conv1D + Bidirectional LSTM...")
#                         pred_scaled = dl_model.predict(scaled_seq)
# 
#                         # Manual scaling back approximation or using Scaler_Y
#                         st.metric(label="Predicted Target Scale output", value=f"{float(pred_scaled[0][0]):.4f}")
#                         st.success("Sequence processing completed successfully!")
#                     else:
#                         st.error("Scaler file 'scaler_X.pkl' missing!")
#             else:
#                 st.error(f"Dataset needs at least {LOOKBACK} rows to construct the input sequence.")
#         else:
#             st.error(f"Uploaded CSV must contain the following columns: {FEATURE_COLS}")
# 
# # --- OPTION 3: Batch CSV Evaluation & Preprocessing ---
# elif model_option == "Batch CSV Upload & Evaluation":
#     st.subheader("📁 Batch Data Clean & Inference")
# 
#     file = st.file_uploader("Upload AirQualityUCI.csv dataset:", type=["csv"])
#     if file is not None:
#         data = pd.read_csv(file)
# 
#         st.write("Raw Input Data Preview:", data.head())
# 
#         # Apply notebook preprocessing
#         data.replace(-200, np.nan, inplace=True)
#         data.dropna(how='all', axis=0, inplace=True)
#         data.dropna(how='all', axis=1, inplace=True)
# 
#         st.write("Missing values count per feature after cleaning:")
#         st.json(data.isnull().sum().to_dict())
# 
#         # Impute missing features
#         if all(col in data.columns for col in FEATURE_COLS):
#             X_batch = data[FEATURE_COLS].copy()
#             X_batch.fillna(X_batch.mean(), inplace=True)
# 
#             if xgb_model is not None:
#                 preds = xgb_model.predict(X_batch)
#                 data['Predicted_CO(GT)'] = preds
# 
#                 st.write("Processed Data with Predictions:", data.head())
# 
#                 # Download Option
#                 csv_download = data.to_csv(index=False).encode('utf-8')
#                 st.download_button("Download Predictions CSV", data=csv_download, file_name="AQI_Predictions.csv", mime="text/csv")

import joblib
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBRegressor
import numpy as np

print(" Generating and saving fallback ML assets...")
scaler_X = MinMaxScaler()
scaler_X.fit(np.random.rand(10, 7))
scaler_y = MinMaxScaler()
scaler_y.fit(np.random.rand(10, 1))
joblib.dump(scaler_X, 'scaler_X.pkl')
joblib.dump(scaler_y, 'scaler_y.pkl')
placeholder_model = XGBRegressor(n_estimators=100, learning_rate=0.5, random_state=42)
placeholder_model.fit(np.random.rand(10, 7), np.random.rand(10, 1))
joblib.dump(placeholder_model, 'xgboost_aqi_model.pkl')
print(" SUCCESS! The following files have been created in your directory:")

import os
print([f for f in os.listdir('.') if f.endswith('.pkl')])

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
import numpy as np

dl_model = Sequential([
    Flatten(input_shape=(24, 7)),
    Dense(64, activation='relu'),
    Dense(1)
])

dl_model.compile(optimizer='adam', loss='mse')

dl_model.save('aqi_deep_learning_model.h5')

